# Generated by Django 5.0.6 on 2024-07-10 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table='comment',
        ),
    ]
